
const issues = [
  "Abortion",
  "Budget Allocation",
  "Climate Change",
  "Economy",
  "Education",
  "Election Integrity",
  "Gun Control",
  "Healthcare",
  "Immigration",
  "Infrastructure",
  "LGBTQ+ Rights",
  "Local Ordinances",
  "Parks and Recreation",
  "Public Safety",
  "Taxes",
  "Zoning Laws",
]

const officeTypes = {
  President: "President",
  Commissioner: "Commissioner",
  Councilmember: "Councilmember",
  DistrictAttorney: "District Attorney",
  Governor: "Governor",
  Judge: "Judge",
  Mayor: "Mayor",
  Senator: "Senator",
  Sheriff: "Sheriff",
  Representative: "Representative",
  VicePresident: "Vice President",
}

const possibleStates = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
  "Guam",
]

export { issues, officeTypes, possibleStates };